- name: Configure NetQ-TS interfaces file
  copy:
    src: ../templates/interfaces
    dest: /etc/network/interfaces

- name: Apply host networking changes
  shell: ifreload -a

- name: Start NetQ agent on NetQ-TS
  shell: netq config restart agent

- name: Configure NetQ Notifier Service
  template:
    src: ../templates/netq.j2
    dest: /etc/netq/netq.yml
  when: not(slack.bgp is none and slack.all is none)

- name: Restart NetQ Notifier Service
  systemd:
    state: restarted
    name: netq-notifier
  when: not(slack.bgp is none and slack.all is none)
